import type React from "react";

export type Params = {
  text: string;
  onClick: () => void;
};

export type Returns = React.JSX.Element;

// Generated by proxyload
export type Variations = "default" | "secondary";

export type Interface = (
  props: Params & { variation?: Variations; version?: string }
) => Returns;
