
// derived from interface files
import type React from "react";

export type Params = {
  text: string;
  onClick: () => void;
};

export type Returns = React.JSX.Element;

export type Interface = (params: Params) => Returns;


// replace the whole import line with and empty string
// This file was generated by proxyload



type Variations = "default" | "secondary";

export type Component_Button = (
  props: Params & { variation?: Variations; version?: string }
) => Returns;

        