
// This file was generated by proxyload

import type { Component_Button } from "./types";

import Button_default from "./default";
import Button_secondary from "./secondary";

type Variations = "default" | "secondary";

export const Button: Component_Button = (props) => {
  const { variation = "default" } = props;
  const variationMap = {
    default: Button_default,
    secondary: Button_secondary,
  };
  return variationMap[variation || "default"]?.(props) ?? variationMap["default"](props);
};
