// This file was generated by proxyload
import type { Params, Returns } from "./interface";

type Variations = "default" | "secondary";

export type Component_Button = (
  props: Params & { variation?: Variations; version?: string }
) => Returns;
