
// This file was generated by proxyload

import type { Component_EmailForm } from "./types";

import EmailForm_default from "./default";

type Variations = "default";

export const EmailForm: Component_EmailForm = (props) => {
  const { variation = "default" } = props;
  const variationMap = {
    default: EmailForm_default,
  };
  return variationMap[variation || "default"]?.(props) ?? variationMap["default"](props);
};
