import type React from "react";

export type Params = {
  count: number;
};

export type Returns = React.JSX.Element;

// Generated by proxyload
export type Variations = "default";

export type Interface = (
  props: Params & { variation?: Variations; version?: string }
) => Returns;
