
// This file was generated by proxyload
import type { Component_Component } from "./types";

import Component_default from "./default";

type Variations = "default";

export const Component: Component_Component = (props) => {
  const { variation = "default" } = props;
  const variationMap = {
    default: Component_default,
  };
  return variationMap[variation || "default"]?.(props) ?? variationMap["default"](props);
};
