
// derived from interface files
import type React from "react";

export type Params = {
  host: string;
  name: string;
  type: string;
  version: string;
  variation: string;
};
export type Returns = React.ComponentType<unknown>;

export type Interface = (params: Params) => Returns;


// replace the whole import line with and empty string
// This file was generated by proxyload



type Variations = "default";

export type Loader_Component = (
  props: Params & { variation?: Variations; version?: string }
) => Returns;

        