// This file was generated by proxyload

import type { Loader_Component } from "./types";

import Component_default from "./default";

export const Component: Loader_Component = (props) => {
  const { variation = "default" } = props;
  return     default: Component_default,[variation || "default"](props);
};
