import type React from "react";

export type Params = {
  host: string;
  name: string;
  type: string;
  hash: string;
  variation: string;
  namespace: string;
  dependencies: Record<string, any>;
};
export type Returns = React.ComponentType<unknown>;

// Generated by proxyload
export type Variations = "default";

export type Interface = (props: Params & { variation?: Variations }) => Returns;
