import type React from "react";

export type Params = {
  host: string;
  name: string;
  type: string;
  version: string;
  variation: string;
};
export type Returns = React.ComponentType<unknown>;

// Generated by proxyload
export type Variations = "default";

export type Interface = (
  props: Params & { variation?: Variations; version?: string }
) => Returns;
