// This file was generated by proxyload

import type { Component_EmailForm } from "./types";

import EmailForm_default from "./default";

export const EmailForm: Component_EmailForm = (props) => {
  const { variation = "default" } = props;
  return     default: EmailForm_default,[variation || "default"](props);
};
