import type React from "react";

export type Params = {
  onSubmit: (val: string) => void;
};

export type Returns = React.JSX.Element;

// Generated by proxyload
type Variations = "default";

export type Component_EmailForm = (
  props: Params & { variation?: Variations; version?: string }
) => Returns;
