// This file was generated by proxyload

import type { Component_Button } from "./types";

import Button_default from "./default";
import Button_secondary from "./secondary";

export const Button: Component_Button = (props) => {
  const { variation = "default" } = props;
  return     default: Button_default,
    secondary: Button_secondary,[variation || "default"](props);
};
